### ISSUE TITLE
Uncaught TypeError: The "data" argument must be one of type string, Buffer, TypedArray, or DataVi...

### ISSUE THREAD

**Issue by dallaire44** [dldl/sphinx-preview#24] opened 2020-06-12 15:47 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Ubuntu 20.04
**Thrown From**: [sphinx-preview](https://github.com/dldl/sphinx-preview) package 0.1.5

### Stack Trace

Uncaught TypeError: The "data" argument must be one of type string, Buffer, TypedArray, or DataView. Received type object

```
At internal/crypto/hash.js:64

TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, Buffer, TypedArray, or DataView. Received type object
    at Hash.update (internal/crypto/hash.js:64:11)
    at Object.getContainerName (/packages/sphinx-preview/lib/sphinx-preview.js:71:24)
    at Object.startSphinxServer (/packages/sphinx-preview/lib/sphinx-preview.js:115:32)
    at Object.toggle (/packages/sphinx-preview/lib/sphinx-preview.js:34:12)
    at HTMLElement.sphinxPreviewToggle (/packages/sphinx-preview/lib/sphinx-preview.js:23:47)
    at CommandRegistry.handleCommandEvent (/snap/atom/252/usr/share/atom/resources/app/static/<embedded>:11:349576)
    at CommandRegistry.dispatch (/snap/atom/252/usr/share/atom/resources/app/static/<embedded>:11:348051)
    at AtomEnvironment.dispatchApplicationMenuCommand (/snap/atom/252/usr/share/atom/resources/app/static/<embedded>:1:725973)
    at EventEmitter.t (/snap/atom/252/usr/share/atom/resources/app/static/<embedded>:1:733896)
    at EventEmitter.emit (events.js:194:13)
```

### Commands

```
     -0:59.2.0 application:open-file (div.welcome.is-guide)
     -0:15.4.0 sphinx-preview:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-html-preview 0.2.6 
browser-plus 0.0.98 
sphinx-preview 0.1.5 
```

**Comment by quentinus95** [comment] 2020-07-15 12:02
Duplicate of #18.

**Closed as completed by quentinus95** 2020-07-15 12:02 UTC
