### ISSUE TITLE
Uncaught The "data" argument must be one of type string, TypedArray, or DataView. Received type o...

### ISSUE THREAD

**Issue by bedengler** [dldl/sphinx-preview#22] opened 2019-12-02 10:45 UTC
I just clicked on Packages -> sphinx-preview -> Toggle

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.13.6
**Thrown From**: [sphinx-preview](https://github.com/dldl/sphinx-preview) package 0.1.5

### Stack Trace

Uncaught The "data" argument must be one of type string, TypedArray, or DataView. Received type object

```
At internal/crypto/hash.js:58

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type object
    at Hash.update (internal/crypto/hash.js:58:11)
    at Object.getContainerName (/packages/sphinx-preview/lib/sphinx-preview.js:71:24)
    at Object.startSphinxServer (/packages/sphinx-preview/lib/sphinx-preview.js:115:32)
    at Object.toggle (/packages/sphinx-preview/lib/sphinx-preview.js:34:12)
    at HTMLElement.sphinxPreviewToggle (/packages/sphinx-preview/lib/sphinx-preview.js:23:47)
    at CommandRegistry.handleCommandEvent (/Applications/Utilities Programmierung/Atom.app/Contents/Resources/app/static/<embedded>:11:349392)
    at CommandRegistry.dispatch (/Applications/Utilities Programmierung/Atom.app/Contents/Resources/app/static/<embedded>:11:347867)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Utilities Programmierung/Atom.app/Contents/Resources/app/static/<embedded>:1:718772)
    at EventEmitter.t (/Applications/Utilities Programmierung/Atom.app/Contents/Resources/app/static/<embedded>:1:726695)
    at EventEmitter.emit (events.js:182:13)
```

### Commands

```
  2x -1:35.8.0 sphinx-preview:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
browser-plus 0.0.98 
convert-file-encoding 0.1.0 
php-analyser 0.2.0 
sphinx-preview 0.1.5 
```

**Comment by quentinus95** [comment] 2020-07-15 12:02
Duplicate of #18.

**Closed as completed by quentinus95** 2020-07-15 12:02 UTC
